### ISSUE TITLE
v10 no_router

### ISSUE THREAD

**Issue by bemble** [fairecasoimeme/Zlinky_TIC#123]
Hi,
I can't find the "no_router" bin file for v10, where can I find it?

**Comment by CladStriffe** [comment]
Hi, the no-routeur firmware is now called "limited". 
Available here 
[](https://github.com/fairecasoimeme/Zlinky_TIC/releases/download/v10.0/ZLinky_router_limited_v10.bin)

OTA update only possible if you are already running a no-routeur firmware. Otherwise you have to use a USB-TTL adapter to upload it on HW.

**Comment by bemble** [comment]
Thank you for this clarification, I’ll upgrade using USB.
