### ISSUE TITLE
ZLinky is not issuing a Device Annoucement after a Power Off/On

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#14]
As stated in the Title when power Off/On of the ZLinky there is no device annoucement !

**Comment by fairecasoimeme** [comment]
This is normal on new firmware mode router because this function is only for device with zigbee 3.0.

[JN-UG-3114.pdf](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjD_LKLvvnzAhWGzYUKHR-iDvIQFnoECAUQAQ&url=https%3A%2F%2Fwww.nxp.com%2Fdocs%2Fen%2Fuser-guide%2FJN-UG-3114.pdf&usg=AOvVaw0eeoeKnZw7S4AQ8j_b28wR)

Page 20

![image](https://user-images.githubusercontent.com/22256438/139831724-3ce7e4b6-7214-4130-8ea4-6226ace428f3.png)

Normally ZLinky can't do a power off/on because it is alimented by general counter. Unlike devices, ZLinky should not be moved. If counter is down coordinator is down too. For me, rejoin on power off/on is not useful.

If really, there is a need, we have to implement on button push but I don't know if it's possible yet

**Comment by pipiche38** [comment]
this deviate from the ZB3.0 devices I have seen so far like Legrand-Netatmo

**Comment by fairecasoimeme** [comment]
To my knowledge they are the only ones who do. But why not. I wonder what is the use

**Comment by pipiche38** [comment]
Up to now, ZLinky is the first router not issuing a Device Annoucement after a Power Off/On

**Comment by fairecasoimeme** [comment]
however for tuya routers like the QS-Zigbee-C0, this is the case.

**Comment by pipiche38** [comment]
I would not use Tuya as a reference. but as it is documented I have close the issue

**Comment by fairecasoimeme** [comment]
unfortunately, we cannot say either that Legrand is uncompromising on the standard. the real question is to know what is the usefulness of this function.

to force a DEVICE ANNOUNCE with a REJOIN, we can use the leave function of the coordinator (E_SL_MSG_LEAVE_REQUEST)

**Comment by pipiche38** [comment]
For me the feature is very simple, it will allow to know that the router has been out of the network a while, since we get a Device Annoucement when powered on.
As you stated it is expected that the ZLinky is always on. However during the test, if I'm recall correctly we have seen the ZLinky having Device Annoucement (when it was configured as a End Device )
