### ISSUE TITLE
Seting Configure Reporting on Cluster 0x0702 fail

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#6]
When doing a Configure Reporting on Cluster 0x0702

We get 0x8c error code on Attribute 0x0000
We get 0x86 error  code on Attribute 0x0400

**Comment by pipiche38** [comment]
Looks like 0x0400 is indeed not a reported attribute, so the error make sense, but not for 0x0000 attribute

**Comment by fairecasoimeme** [comment]
0x8c error seems to be this kind of error :  ZPS_APL_ZDP_E_TABLE_FULL          			= 0x8c
For the moment there is only 5 configure report available. I should increase this value

**Comment by pipiche38** [comment]
still valid on latest firmware

**Comment by fairecasoimeme** [comment]
Hi,
It's a mistake. the right error is : E_ZCL_CMDS_UNREPORTABLE_ATTRIBUTE : 0x8c
This error is given by coordinator because it's table on this attribute is not reportable but the ZLinky ignore this message and add to its reportable table.

I'll modify reportable on ZiGate new version but this kind of error could occur to the others coordinators

**Comment by pipiche38** [comment]
Is that not vice-versa. This UNREPORTABLE ATTRIBUTE is provided by the ZLinky when setting a Configure Reporting !

**Comment by fairecasoimeme** [comment]
I'm going to recheck to be sure.

**Comment by fairecasoimeme** [comment]
finally, you're right, there is a bug and it's fixed for next firmware
